title: Machinery's Design Handbook
description: Refs, Defs and Specs for Machine Designers; the initiated and the curious.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Machines that Make: https://mtm.cba.mit.edu/