# Processes

## Machining

### Stiffness and Chatter[^chatter] {#sec-machining-chatter}

We want stiffness in our machines first because it means our positioning stages will be more accurate: if we command a motor to some position, but our machine is under load (gravity, some cutting force, etc), we will miss our target position by whatever the machine's deflection at that force is. For example given the belt example in @sec-fund-stiffness, with only 50N of cutting force our machine will miss by one whole millimeter (this is also why machine designers get excited about i.e. linear encoders mounted directly on-axis). 

This becomes more complex, though, when we have resonance and dynamics to think about. For example in a milling machine we see large cutting forces, but those forces are exerted at a (normally quite high) frequency (proportional to our spindle speed and flute count). If cutting forces excite our machine structure near it's natural frequency (or one of its harmonics), we are more likely to see chatter - which we can see in slo-mo in this excellent video from `Breaking Taps` 

<iframe width="560" height="315" src="https://www.youtube.com/embed/aog0syGaZzQ?start=148" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

For example, if we have a spindle rotating at 6000 RPM, we have a rotational frequency of 100Hz (RPM / 60 = Hz). With four flutes, we are making a chip (and loading the machine's structure) at 400Hz (or once every 2.5 milliseconds). We can hear these frequencies when we machine, and experienced machinists rely on that input extensively. 

Machines all have resonant frequencies, which are related to their stiffness (proportional) and mass (inversely):

$$
\omega = \sqrt{\frac{k}{m}}
$$

If we increase stiffness, we raise the resonant frequency - and if we add mass, we lower it (mass serving as a kind of damper). This might mean that, for our stiffness goal, we need to add lots of mass in order to lower the resonant frequency below the range of our expected excitation forces - or we might need to increase our stiffness in order to move the resonant freqency well above that range. 

[^chatter]: Not sure if this is appropriate here or an aside... and probably my reasoning is worth checking. It may be a good idea to work this up as an example as well? 
[^stepper-stiffness]: This would be another good nugget to expand on. Get the dyno out... 
[^whereis-classic]: This should link to classical control, where we can discuss in more depth the relationship between a controller's $$K$$, its stiffness, and how i.e. bandwidth relates to how much $$K$$ we can dial in, etc etc... 